export const DC_MODULE_CONFIG = {
  key: 'DC',
  label: 'DC CABLE PULLING PROGRESS TRACKING',
  csvFormat: 'dc',
  csvPath: '/dc-cable-pulling-progress/dc_strings.csv',
  linkPath: '/dc-cable-pulling-progress/link',
  stringTextVisibility: 'always', // 'always' | 'hover' | 'none'
  stringTextToggle: false,
  stringTextDefaultOn: true,
  geojsonFiles: [
    { url: '/dc-cable-pulling-progress/full.geojson', name: 'full', color: 'rgba(255,255,255,0.55)', fillColor: 'transparent' },
    { url: '/dc-cable-pulling-progress/string_text.geojson', name: 'string_text', color: '#dc2626', fillColor: '#ef4444' },
    { url: '/dc-cable-pulling-progress/inv_id.geojson', name: 'inv_id', color: '#16a34a', fillColor: '#22c55e' },
    {
      url: '/dc-cable-pulling-progress/lv_box.geojson',
      name: 'lv_box',
      color: '#eab308',
      fillColor: '#facc15',
      weight: 3,
    },
    {
      url: '/dc-cable-pulling-progress/boundry.geojson',
      name: 'boundry',
      color: 'rgba(239, 68, 68, 0.7)',
      fillColor: 'transparent',
      weight: 1.2,
      fillOpacity: 0,
      interactive: false,
    },
  ],
};

export const MC4_MODULE_CONFIG = {
  key: 'MC4',
  label: 'MC4 Installation',
  // Files live in: public/MC4_INSTALLATION_AND_DC_TERMINATION_PROGRESS_TRACKING/
  csvFormat: 'mc4_strings',
  csvPath: '/MC4_INSTALLATION_AND_DC_TERMINATION_PROGRESS_TRACKING/dc_strings.csv',
  linkPath: '/MC4_INSTALLATION_AND_DC_TERMINATION_PROGRESS_TRACKING/link',
  // Spec override: MC4 totals must show 9517 in both sub-modes.
  mc4TotalEnds: 9517,
  // Spec: CSV contains 9056 strings -> total endpoints = 9056 * 2 = 18112
  mc4DefaultStrings: 9056,
  // Render inv_id points as LV-style text plates (visual only; not clickable completion).
  invIdLabelMode: true,
  // Match LV/DC inv_id appearance
  invIdTextScale: 0.8,
  invIdTextBaseSize: 12,
  invIdTextStyle: '600',
  invIdTextMinFontSize: 7,
  invIdTextMaxFontSize: 14,
  invIdTextRefZoom: 20,
  invIdTextStrokeColor: 'rgba(0,0,0,0.8)',
  invIdTextStrokeWidthFactor: 1.0,
  invIdTextBgColor: null,
  invIdTextBgPaddingX: 0,
  invIdTextBgPaddingY: 0,
  invIdTextBgStrokeColor: null,
  invIdTextBgStrokeWidth: 0,
  invIdTextBgCornerRadius: 0,
  invIdDoneTextColor: 'rgba(34,197,94,1)',
  invIdDoneTextColorNoBg: 'rgba(34,197,94,1)',
  invIdDoneBgColor: null,
  invIdDoneBgStrokeColor: null,
  invIdDoneBgStrokeWidth: 0,
  invIdHighlightTextColor: 'rgba(249,115,22,1)',
  invIdHighlightBgColor: null,
  invIdHighlightBgStrokeColor: null,
  invIdHighlightBgStrokeWidth: 0,
  invIdTextMinTextZoom: 17,
  invIdTextMinBgZoom: 99,
  // MC4: render ONLY subs_text labels (map subs_text.geojson to shared string_text renderer).
  stringTextVisibility: 'always',
  stringTextToggle: false,
  stringTextDefaultOn: false,
  // subs_text styling
  stringTextColor: 'rgba(250,204,21,0.65)',
  stringTextBaseSize: 22,
  stringTextStyle: '400',
  stringTextStrokeColor: 'rgba(0,0,0,0.85)',
  stringTextStrokeWidthFactor: 1.2,
  stringTextMinZoom: 0,
  stringTextMinFontSize: 14,
  stringTextMaxFontSize: 26,
  stringTextRefZoom: 20,
  geojsonFiles: [
    {
      url: '/MC4_INSTALLATION_AND_DC_TERMINATION_PROGRESS_TRACKING/full.geojson',
      name: 'full',
      color: '#2563eb',
      fillColor: '#3b82f6',
    },
    // Feed subs_text into the existing \"string_text\" rendering path.
    { url: '/MC4_INSTALLATION_AND_DC_TERMINATION_PROGRESS_TRACKING/subs_text.geojson', name: 'string_text', color: '#dc2626', fillColor: '#ef4444' },
    {
      url: '/MC4_INSTALLATION_AND_DC_TERMINATION_PROGRESS_TRACKING/subs.geojson',
      name: 'subs',
      color: '#94a3b8',
      fillColor: '#94a3b8',
    },
    {
      url: '/MC4_INSTALLATION_AND_DC_TERMINATION_PROGRESS_TRACKING/inv_id.geojson',
      name: 'inv_id',
      color: '#16a34a',
      fillColor: '#22c55e',
    },
    {
      url: '/MC4_INSTALLATION_AND_DC_TERMINATION_PROGRESS_TRACKING/lv_box.geojson',
      name: 'lv_box',
      color: '#eab308',
      fillColor: '#facc15',
      weight: 3,
      fillOpacity: 0.6,
    },
    {
      // Boundary: render + style must match DC
      url: '/MC4_INSTALLATION_AND_DC_TERMINATION_PROGRESS_TRACKING/boundry.geojson',
      name: 'boundry',
      color: 'rgba(239, 68, 68, 0.7)',
      fillColor: 'transparent',
      weight: 1.2,
      fillOpacity: 0,
      interactive: false,
    },
  ],
};
